services:
  web:
    image: gitlab-rs-ce-m:latest
    container_name: gitlab-rs
    restart: unless-stopped
    hostname: bak.toarujs.com
    shm_size: '256m'
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 300s
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://bak.toarujs.com:9071'
        gitlab_rails['gitlab_shell_ssh_port'] = 9078
        postgresql['enable'] = false
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "xK9m-2pQ7-rL4w-vN8j"
        gitlab_rails['db_host'] = "db"
        redis['enable'] = false
        gitlab_rails['redis_host'] = "redis"
        nginx['enable'] = false
        gitlab_workhorse["enable"] = false
        gitlab_rails['trusted_proxies'] = ['172.16.0.0/12', '192.168.0.0/16', '10.0.0.0/8', '172.29.0.0/16']
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['initial_root_password'] = 'T0aruJ5w0rkH0rs3'
    ports:
      - "9070:80"
      - "9078:22"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    depends_on:
      - db
      - redis
    networks:
      - gitlab-rs-net

  db:
    image: postgres:17
    container_name: gitlab-rs-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: "xK9m-2pQ7-rL4w-vN8j"
      POSTGRES_DB: gitlabhq_production
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - gitlab-rs-net

  redis:
    image: redis:7
    container_name: gitlab-rs-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis:/data
    networks:
      - gitlab-rs-net

networks:
  gitlab-rs-net:
    name: gitlab-rs-bridge
    driver: bridge
