syntax = "proto3";

package gitaly;

option go_package = "gitlab.com/gitlab-org/gitaly/v16/proto/go/gitalypb";

import "gitaly/smarthttp.proto";

message GetArchiveRequest {
  Repository repository = 1;
  string commit_id = 2;
  string prefix = 3;
  Format format = 4;
  bytes path = 5;
  repeated bytes exclude = 6;
  bool elide_path = 7;
  bool include_lfs_blobs = 8;

  enum Format {
    ZIP = 0;
    TAR = 1;
    TAR_GZ = 2;
    TAR_BZ2 = 3;
  }
}

message GetArchiveResponse {
  bytes data = 1;
}

message GetSnapshotRequest {
  Repository repository = 1;
  string commit_id = 2;
}

message GetSnapshotResponse {
  bytes data = 1;
}

service RepositoryService {
  rpc GetArchive(GetArchiveRequest) returns (stream GetArchiveResponse);
  rpc GetSnapshot(GetSnapshotRequest) returns (stream GetSnapshotResponse);
}
